name: Continuous Integration

on:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Chequear el repositorio
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalar dependencias
        run: |
          npm init -y
          npm install --save-dev mocha

      - name: Ejecutar prueba unitaria
        run: npx mocha test.js
